seqan/chopper

include/chopper/pack/hierarchical_binning.hpp, test/api/pack/chopper_pack_test.cpp, test/api/pack/hierarchical_binning_test.cpp, test/cli/cli_chopper_pipeline_test.cpp
I added the level factor from the paper.
The results for the small data sets now have 2 levels instead of 4 and 5.
Some tests fail, but I am not sure whether I broke something or the result is just different/better now.
=> Add factor for needed recursive levels

include/chopper/union/user_bin_sequence.hpp, test/api/union/CMakeLists.txt, test/api/union/user_bin_sequence_test.cpp
Doesn't increase the coverage yet I think. 
But good to have anyway.
=> [TEST] First few test for the user_bin_sequence class

test/api/union/user_bin_sequence_test.cpp
=> [NOP] Some clean up in user_bin_sequence_test.

src/chopper_split.cpp, test/api/split/chopper_split_test.cpp, test/cli/cli_chopper_basic_test.cpp
While working on this I think I will stop after this PR with working on chopper split now and move everythin related to it to a different branch because the splitting does not work with the current hierarchical IBF anyway. Once I adjust that i can revive the branch
=> [TEST,NOP] Add chopper split cmd test and refactor parsing a bit.

include/chopper/helper.hpp, include/chopper/pack/hibf_statistics.hpp, include/chopper/pack/hierarchical_binning.hpp, include/chopper/pack/pack_config.hpp, include/chopper/pack/pack_data.hpp, include/chopper/pack/simple_binning.hpp, src/chopper_pack.cpp, test/api/CMakeLists.txt, test/api/helper_test.cpp, test/api/pack/chopper_pack_estimation_test.cpp, test/api/pack/hierarchical_binning_test.cpp, test/api/pack/simple_binning_test.cpp, test/cli/CMakeLists.txt, test/cli/cli_chopper_pack_statistics_test.cpp
follow up of https://github.com/seqan/chopper/pull/47
Closes https://github.com/seqan/chopper/pull/47
=> [FEATURE] Output detailed statistics if requested.

include/chopper/union/user_bin_sequence.hpp, test/api/union/user_bin_sequence_test.cpp
Should raise union coverage to a 100
=> [TEST] Add cluster_bins test and some asserts.

include/chopper/layout/hibf_statistics.hpp, src/chopper_layout.cpp, test/cli/cli_chopper_layout_statistics_test.cpp
Follow up to https://github.com/seqan/chopper/pull/69
=> New chopper layout output with fixed tests

include/chopper/count/count_kmers.hpp, include/chopper/count/output.hpp
I'll start to tackle that the sketches work with aggregating.
This is some refactoring before that.
=> [NOP] Outsource output function.

include/chopper/layout/arrange_user_bins.hpp, include/chopper/layout/data_store.hpp, include/chopper/layout/hibf_statistics.hpp, include/chopper/layout/hierarchical_binning.hpp, include/chopper/layout/simple_binning.hpp, src/chopper_layout.cpp, test/api/layout/aggregate_by_test.cpp, test/api/layout/hibf_statistics_test.cpp, test/api/layout/hierarchical_binning_test.cpp
instead of having it in every return value.
=> [MISC] store total_query_cost in data.

include/chopper/layout/data_store.hpp, include/chopper/layout/hierarchical_binning.hpp, include/chopper/layout/ibf_query_cost.hpp, include/chopper/layout/simple_binning.hpp, src/chopper_layout.cpp, test/api/layout/ibf_query_cost_test.cpp
To show that is works. This first PR has the same values as before for every FPR.
(which is basically how it is done now anyway)
A follow up PR will change the values.
=> [MISC] Make query_cost deppend on FPR.

.clang-format, .gitmodules, CMakeLists.txt, include/chopper/count/execute.hpp, src/CMakeLists.txt, src/chopper.cpp, src/chopper_layout.cpp, src/measure_hyperloglog.cpp
=> [MISC] Use the sharg-parser

test/api/layout/execute_with_estimation_test.cpp
=> [TEST] Fix warning in test.

include/chopper/count/count_kmers.hpp, include/chopper/data_store.hpp, include/chopper/layout/arrange_user_bins.hpp, include/chopper/layout/hierarchical_binning.hpp, include/chopper/sketch/estimate_kmer_counts.hpp, include/chopper/sketch/user_bin_sequence.hpp, test/api/count/count_kmers_test.cpp, test/api/count/execute_test.cpp, test/api/layout/execute_with_estimation_test.cpp, test/api/sketch/hyperloglog_test.cpp, test/api/sketch/user_bin_sequence_test.cpp
=> [MISC] Use sketches from count_kmers instead of reading them from disk.

include/chopper/configuration.hpp, src/chopper.cpp, src/chopper_layout.cpp, test/api/count/count_kmers_test.cpp, test/api/count/execute_test.cpp, test/api/layout/execute_layout_test.cpp, test/api/layout/execute_with_estimation_test.cpp, test/api/layout/hibf_statistics_test.cpp, test/cli/cli_chopper_pipeline_test.cpp
Prefix is not needed anymore because of #127 and #129
=> [MISC] Remove prefixes and just use variable sketch_directory.

test/api/api_test.hpp, test/api/count/count_kmers_test.cpp, test/api/count/execute_test.cpp, test/api/layout/execute_layout_test.cpp, test/api/layout/execute_with_estimation_test.cpp, test/api/layout/hibf_statistics_test.cpp, test/api/sketch/hyperloglog_test.cpp, test/api/sketch/user_bin_sequence_test.cpp, test/cli/cli_chopper_basic_test.cpp, test/cli/cli_chopper_pipeline_test.cpp
Quick fix of #131 
Blocked by https://github.com/seqan/seqan3/issues/3126
=> [INFRA] Update seqan3 submodule to current master

include/chopper/sketch/estimate_kmer_counts.hpp, src/chopper.cpp, test/api/layout/execute_with_estimation_test.cpp
=> [MISC] Make estimate_kmer_counts independent of data_store.

test/api/layout/execute_with_estimation_test.cpp
=> [TEST] Add explicit layout test for --determine-bast-tmax.

include/chopper/data_store.hpp, include/chopper/layout/hierarchical_binning.hpp, include/chopper/layout/layout.hpp, include/chopper/layout/output.hpp, include/chopper/layout/previous_level.hpp, include/chopper/layout/print_result_line.hpp, include/chopper/layout/simple_binning.hpp, src/chopper.cpp, src/chopper_layout.cpp, test/api/layout/CMakeLists.txt, test/api/layout/execute_layout_test.cpp, test/api/layout/execute_with_estimation_test.cpp, test/api/layout/hibf_statistics_test.cpp, test/api/layout/hierarchical_binning_test.cpp, test/api/layout/layout_test.cpp, test/api/layout/simple_binning_test.cpp
Big step towards having an HIBF data structure that does layouting and building without storing the layout in between.
=> [MISC] Store layout in a struct instead of writing directly to stream.

include/chopper/layout/output.hpp, include/chopper/prefixes.hpp
blocked by https://github.com/seqan/chopper/pull/156/files
=> [FEATURE] New prefix for the first header line.

.github/workflows/ci_lint.yml
Check whether there is something to commit:
* yes: Commit+push and do no remove label. lint CI will run again on the pushed commit.
* no: Remove label. Other CI will run.
This should fix the weird cancellations when the lint CI pushes something.
=> [INFRA] improve lint CI

include/chopper/sketch/toolbox.hpp
=> [MISC] Make member functions of toolbox const.

include/chopper/data_store.hpp, include/chopper/sketch/execute.hpp, include/chopper/sketch/read_data_file.hpp, src/chopper.cpp, test/api/layout/execute_with_estimation_test.cpp, test/api/sketch/execute_test.cpp, test/api/sketch/read_data_file_test.cpp
=> [Misc] Make sketching independent of chopper::data_store.

include/chopper/data_store.hpp, include/chopper/layout/compute_fp_correction.hpp, src/chopper_layout.cpp, test/api/layout/fp_correction_test.cpp, test/api/layout/hibf_statistics_test.cpp, test/api/layout/hierarchical_binning_test.cpp
=> [MISC] Make compute_fp_correction independent from data_store.

include/chopper/data_store.hpp, include/chopper/layout/execute.hpp, include/chopper/layout/hibf_statistics.hpp, include/chopper/layout/hierarchical_binning.hpp, include/chopper/layout/layout.hpp, include/chopper/layout/output.hpp, include/chopper/layout/simple_binning.hpp, include/chopper/sketch/check_filenames.hpp, include/chopper/sketch/execute.hpp, include/chopper/sketch/toolbox.hpp, src/chopper.cpp, src/chopper_layout.cpp, test/api/layout/execute_layout_test.cpp, test/api/layout/execute_with_estimation_test.cpp, test/api/layout/hibf_statistics_test.cpp, test/api/layout/hierarchical_binning_test.cpp, test/api/layout/layout_test.cpp, test/api/layout/simple_binning_test.cpp, test/api/sketch/execute_test.cpp, test/api/sketch/toolbox_test.cpp
Big step towards the HIBF lib that can take a range of sequences instead of files because the input must not be modifyable (sortable).
=> [MISC] Do not change the input order but relative postitions.

include/chopper/layout/hierarchical_binning.hpp
=> [MISC] Remove unneccessary parameter of process_merged_bin

include/chopper/layout/hierarchical_binning.hpp, include/chopper/sketch/toolbox.hpp
=> [MISC] Remove unneccessary parameters from estimate_interval.

include/chopper/layout/hierarchical_binning.hpp
=> [MISC] Remove unnecessary parameters from process_merged_bin.

include/chopper/layout/hibf_statistics.hpp, include/chopper/layout/hierarchical_binning.hpp, include/chopper/layout/simple_binning.hpp, test/api/layout/hibf_statistics_test.cpp
=> [MISC] Remove dependence on positions in hibf_statistics.

include/chopper/set_up_parser.hpp
=> [DOC] Remove mentions of --rearrange-user-bins

include/chopper/layout/layout.hpp, src/chopper_layout.cpp
needed in order for the layout to be complete / store all necessary information for building
=> [MISC] Store top-level maximum bin index in layout.

include/chopper/sketch/check_filenames.hpp, src/chopper.cpp, test/api/sketch/CMakeLists.txt, test/api/sketch/check_filenames_test.cpp, test/cli/cli_chopper_basic_test.cpp
This throw was lost in the refactoring
=> [FEATURE] Throw helpful exception if file path does not exist.

CMakeLists.txt
If alrady added by someone else
=> [INFRA] Do not add fetch_content modules twice

README.md, include/chopper/configuration.hpp, include/chopper/set_up_parser.hpp, src/chopper.cpp, src/measure_hyperloglog.cpp, test/cli/cli_chopper_basic_test.cpp, test/cli/cli_chopper_pipeline_test.cpp
* Use same parameter names as in raptor
* Add a synopsis, I add the app name "chopper" here, but I'll add "raptor layout" in raptor. I can't use the `info.app_name`, because it is `Raptor-layout`.
=> [MISC] Update argument parsing

.github/workflows/ci_coverage.yml, .github/workflows/ci_linux.yml, .github/workflows/ci_macos.yml, src/display_layout/sizes.cpp
We need display layout tests :D
=> [FIX] Fix insert iterator for display_layout after hubf update.

test/api/layout/execute_layout_test.cpp, test/api/layout/execute_with_estimation_test.cpp
=> [LIB] Update hibf lib.

.codecov.yml, .github/workflows/ci_coverage.yml
Such that Codecov bot can always report status on PR (rate limit)
=> [INFRA] Add token to .codecov.yml

src/util/display_layout/general.cpp, src/util/display_layout/sizes.cpp
=> [FIX] Move values in clang workaround

src/CMakeLists.txt
=> [INFRA] Update chopper_lib target

include/chopper/configuration.hpp, src/layout/execute.cpp, src/set_up_parser.cpp, test/cli/CMakeLists.txt, test/cli/cli_timing_output_test.cpp
=> [FEATURE] Add --timing-output and Output layout timings.

include/chopper/configuration.hpp, test/api/layout/hibf_statistics_test.cpp
There was still a mention of chopper count which is highly outdated.
=> [MISC] Restructure configuration.

test/cli/CMakeLists.txt, test/cli/cli_test.hpp, test/cli/util_display_layout_test.cpp
=> [TEST] Add display_layout tests.

src/util/display_layout/display_layout.cpp, src/util/display_layout/general.cpp, src/util/display_layout/shared.hpp, test/cli/util_display_layout_test.cpp
=> [FEATURE] Only output shared kmers on cmd request.
