seqan/chopper

- src/chopper.cpp
- test/cli/CMakeLists.txt
- test/cli/cli_chopper_basic_test.cpp
- test/cli/cli_chopper_split_test.cpp
Note that I changed the error code handling because the return 0 at the end was unreachable because an unknown submodule is already caught beforehand.
> [TEST, NOP] Add chopper basic test. Change unreachable code.

- src/chopper_layout.cpp
Before Mitra uses chopper we might hide confusing parameters for now.
With the aggregating I'm not sure anymore if it makes sense in chopper layout but only in chopper count. So this option is hidden completely.
> [MISC] Hide aggregate by option for now and make alpha advanced

- src/chopper_layout.cpp
We must use the interpolation here, because there is no exact data for the t_max ~ sqrt(#UBs) case. For the other values it won't make a difference, because the interpolation checks whether there is exact data available.
> [FIX] Call interpolated query cost function

- include/chopper/layout/configuration.hpp
- include/chopper/layout/data_store.hpp
- include/chopper/layout/hibf_statistics.hpp
- include/chopper/layout/hierarchical_binning.hpp
- include/chopper/layout/previous_level.hpp
- include/chopper/layout/simple_binning.hpp
- src/chopper_layout.cpp
Now that we understood how the query cost is gathered, I think this refactoring makes it much more easy to understand since the cost is only collected when a split bin is added. 
In the end everything is added up. Done.
Review commit by commit for a better understanding of the step wise refactoring.
> [MISC] Collect estimated query costs in hibf_statistics.

- include/chopper/cereal/path.hpp
- include/chopper/count/configuration.hpp
- include/chopper/count/count_kmers.hpp
- include/chopper/layout/arrange_user_bins.hpp
- include/chopper/layout/configuration.hpp
- include/chopper/layout/hibf_statistics.hpp
- include/chopper/layout/hierarchical_binning.hpp
- include/chopper/layout/output.hpp
- include/chopper/prefixes.hpp
- src/chopper_count.cpp
- src/chopper_layout.cpp
- test/api/count/count_kmers_test.cpp
- test/api/layout/execute_layout_test.cpp
- test/api/layout/execute_with_estimation_test.cpp
- test/api/layout/execute_with_hll_test.cpp
- test/api/layout/hibf_statistics_test.cpp
- test/api/layout/hierarchical_binning_test.cpp
- test/cli/cli_chopper_basic_test.cpp
- test/cli/cli_chopper_layout_statistics_test.cpp
- test/cli/cli_chopper_pipeline_test.cpp
Alternative to #82 by using cereal.
I don't know if the escaping of `\"` looks right in files. I'll check.
an example now looks like this (I only included two parameters for aesthetic reasons)
```
##CONFIG:
##{
##ENDCONFIG
#HIGH_LEVEL_IBF max_bin_id:0
#FILES  BIN_INDICES     NUMBER_OF_BINS
file1   0       3
file2   3       11
file3   14      50
```
> [FEATURE] Output config in layout file.

- include/chopper/layout/hierarchical_binning.hpp
- test/api/layout/execute_layout_test.cpp
I think this doesn't affect data with large kmer counts but still we should be consistent.
In `simple_binning.hpp` we always round up but in `hierarchical_binning.hpp` we round down.
Since we use the kmer counts to estimate the IBF size given a FPR rate we should round up, since that way we make sure to keep the desired FPR.
> [FIX] Always round up kmer count when splitting bins.

- include/chopper/layout/hibf_statistics.hpp
- include/chopper/layout/hierarchical_binning.hpp
- include/chopper/layout/simple_binning.hpp
- test/api/layout/hibf_statistics_test.cpp
While working on adding merged bin similarities in the query cost estimation, I first refactored the code s.t. the query cost estimation computation is within a single function and not splattered across the code.
Best reviewed commit by commit to understand the individual steps. 
But it is not too important because it is just a refactoring. None of the tests had to be changed/adapted except one: `hibf_statistics_test.cpp` which tests the `hibf_statistics` class independently from the DP algorithm. Since I compute the query costs within `hibf_statistics` now, they also had to be added in this test.
> [MISC] Move computation of estimated query cost into hibf_statistics.

- include/chopper/count/output.hpp
- test/api/layout/execute_with_estimation_test.cpp
The change in `include/chopper/count/output.hpp` was necessary because I used the same files over and over again in the test and usually they get clustered together because the filename is used as a key in the filename_cluster map. Therefore I added dummy information in the second column. But then the hll sketch files were named after the dummy key instead of the filename. This small change fixes that.
But it only works correctly if there is exactly one file per key. The if clause catches this so it's safe for now.
> [TEST] Add determine best tmax test with rearrangement.

- include/chopper/layout/hibf_statistics.hpp
- include/chopper/layout/hierarchical_binning.hpp
- include/chopper/layout/simple_binning.hpp
- include/chopper/sketch/user_bin_sequence.hpp
- test/api/layout/CMakeLists.txt
- test/api/layout/execute_with_estimation_test.cpp
- test/api/sketch/user_bin_sequence_test.cpp
Depends on #98 To see the difference in the test when introducing similarities.
data: RefSeq CompleteGenomes Archea/Bacteria
Query cost **before** this change:
```
tmax  c_tmax  l_tmax  m_tmax (l*m)_tmax  size
----------------------------------------------
64      1.00    2.91    1.00    2.91    292GiB
128     1.20    2.75    0.81    2.22    235GiB
192     1.28    2.51    0.69    1.74    202GiB
256     1.36    2.59    0.68    1.75    197GiB
512     2.01    3.34    0.70    2.33    204GiB
1024    2.64    3.84    0.77    2.97    226GiB
2048    3.37    4.47    0.88    3.92    256GiB
4096    5.98    6.96    0.95    6.62    277GiB
8192    9.92    10.65   0.83    8.88    243GiB
```
Query cost **after** this change:
```
tmax  c_tmax  l_tmax  m_tmax (l*m)_tmax  size …
```
> [FEATURE] Improve query cost estimation (l_tmax) with hll sketches

- include/chopper/layout/arrange_user_bins.hpp
- include/chopper/layout/data_store.hpp
- include/chopper/layout/hierarchical_binning.hpp
- include/chopper/sketch/user_bin_sequence.hpp
- test/api/sketch/user_bin_sequence_test.cpp
This PR significantly lowers the memory consumption at the cost of performance (not tracked).
Instead of storing all interval union estimations in a matrix of size `#user bins x #user bins` we now only store a single vector of size `#user bins` when computing the current column in the DP algorithm.
When backtracking the optimal path, union estimations are computed again for certain merged bins but only if statistics are required so the performance drop is fine.
> [FEATURE] Do not compute the full union estiamtion matrix.

- include/chopper/layout/hibf_statistics.hpp
- src/chopper_layout.cpp
- test/api/layout/execute_with_estimation_test.cpp
- test/api/layout/hibf_statistics_test.cpp
- test/cli/cli_chopper_layout_statistics_test.cpp
Commit 1 just adds some spaces. We usually use spaces...
Commit 2 sets the best tmax as tmax. The tests check whether the `"tmax": 256` line exists in the config.
> [FIX] Wrong t_max in output

- include/chopper/helper.hpp
- test/api/helper_test.cpp
- test/api/layout/execute_with_estimation_test.cpp
- test/api/layout/hibf_statistics_test.cpp
- test/cli/cli_chopper_layout_statistics_test.cpp
Todo: 
Questions:
---
I added Exbibyte such that I avoid unintended behaviour for big numbers
> [MISC] byte formatting

- src/CMakeLists.txt
I noticed that the target binary `measure_hyperloglog` is always built, even when you only build chopper as a submodule (e.g. for raptor). I created this binary to do some measurements for my bachelor thesis. I think it makes sense to not build it by default.
> Make not building measure_hyperloglog the default

- .github/workflows/ci_linux.yml
- .github/workflows/ci_macos.yml
- include/chopper/layout/filenames_data_input.hpp
- include/chopper/layout/hibf_statistics.hpp
- src/CMakeLists.txt
- test/CMakeLists.txt
- test/cmake/chopper_require_test.cmake
Don't override flags with `-w`, and make cli_test dependent on `measure_hyperloglog` such that it is built when building tests.
Also, don't set `-Werror` globally, as we don't care about warnings when building gtest.
> [TEST] Enable warnings

- include/chopper/set_up_parser.hpp
- src/chopper.cpp
- test/cli/cli_chopper_pipeline_test.cpp
Instead of always writing the sketches and disabling that with `--disable-sketch-output`, the sketches will now never be written unless the user specifically sets `--output-sketches-to PATH` on the command line.
> [MISC] Output sketches on cli command.

- include/chopper/configuration.hpp
`version` can't be const for deserialisation
> [FIX] Serialisation of configuration

- include/chopper/layout/hierarchical_binning.hpp
- include/chopper/sketch/toolbox.hpp
- test/api/sketch/toolbox_test.cpp
Makes no sense to store an instance of `chopper::sketch::toolbox` just to use something that could be used as a "free function" also.
> [MISC] Make precompute_union_estimates_for static.

- include/chopper/data_store.hpp
- include/chopper/layout/hibf_statistics.hpp
- include/chopper/layout/hierarchical_binning.hpp
- include/chopper/layout/simple_binning.hpp
- src/chopper_layout.cpp
- test/api/layout/hibf_statistics_test.cpp
- test/api/layout/hierarchical_binning_test.cpp
- test/api/layout/simple_binning_test.cpp
Maybe the last big step, separating chopper stuff from just the layout algorithm that will move to the HIBF lib. Statistics will not move with it.
> [MISC] Rip out hibf_statistic from layout algorithm.

- src/util/display_layout/general.cpp
> [FEATURE] parallel display_layout general

- src/util/display_layout/compute_ibf_size.hpp
- src/util/display_layout/sizes.cpp
- test/api/display_layout/CMakeLists.txt
- test/api/display_layout/compute_ibf_size_test.cpp
This makes sure that display_layout in chopper does not compute wrong sizes but is in sync with the hibf lib function `construct_ibf`
Todo:
> [TEST] Add compute_ibf_size test.

- include/chopper/workarounds.hpp
- src/layout/hibf_statistics.cpp
For example, Debug mode and O2
> [MISC] Add workaround for gcc13's bogus memmov warnings

- include/chopper/input_functor.hpp
- include/chopper/layout/execute.hpp
- include/chopper/layout/output.hpp
- include/chopper/sketch/check_filenames.hpp
- include/chopper/sketch/read_data_file.hpp
- src/chopper.cpp
- src/input_functor.cpp
- src/layout/execute.cpp
- src/layout/output.cpp
- src/sketch/check_filenames.cpp
- src/sketch/read_data_file.cpp
- test/api/layout/execute_layout_test.cpp
- test/api/layout/execute_with_estimation_test.cpp
- test/api/layout/hibf_statistics_test.cpp
- test/api/layout/user_bin_io_test.cpp
- test/api/sketch/check_filenames_test.cpp
- test/api/sketch/read_data_file_test.cpp
- test/cli/util_display_layout_test.cpp
Fixes https://github.com/seqan/chopper/issues/196
> [FEATURE] Allow multiple filenames per user bin.

- include/chopper/layout/determine_best_number_of_technical_bins.hpp
- src/layout/determine_best_number_of_technical_bins.cpp
- src/layout/execute.cpp
This will also simplify to later on read sketches from a file instead of computing them.
> [MISC] determine_best_tmax should not compute its own sketches.

- src/CMakeLists.txt
- src/layout/CMakeLists.txt
- src/sketch/CMakeLists.txt
- src/util/CMakeLists.txt
- src/util/display_layout/CMakeLists.txt
Nothing really changed besides:
* adding aliases (`chopper::*`)
* having interface separately (`chopper::interface`)
> [INFRA] Streamline libraries

- src/chopper_layout.cpp
- test/cli/cli_chopper_layout_from_sketch_file.cpp
I actually run into that warning and was confused :D turned out to be a doc-bug
> [FIX,DOC] Fix warning output for differing kmer sizes.

- src/util/display_layout/general.cpp
- test/cli/util_display_layout_test.cpp
I had a case with a few merged bins within several single bins.
The current display layout looked like this: 
[default.layoutsub171.layout.sizes.general.pdf](https://github.com/user-attachments/files/17473475/default.layoutsub171.layout.sizes.general.pdf)
Which is not really the actual case. Merged bins are size corrected with the relaxed FPR within the DP while split bins are corrected for multiple testing. I incoorporated this into display_layout. Now it looks like this:
[default.layoutsub171.layout.new.general.pdf](https://github.com/user-attachments/files/17473503/default.layoutsub171.layout.new.general.pdf)
which makes more sense for a result of the DP algorithm.
> [UTIL,FEATURE] display_layout: Also compute FPR corrected sizes.
